\ AMIGA JForth Include file.
decimal
EXISTS? DEVICES_KEYBOARD_H NOT .IF
: DEVICES_KEYBOARD_H ;
EXISTS?  EXEC_IO_H NOT .IF
include ji:exec/io.j
.THEN

CMD_NONSTD  0 +  constant KBD_READEVENT
CMD_NONSTD  1 +  constant KBD_READMATRIX
CMD_NONSTD  2 +  constant KBD_ADDRESETHANDLER
CMD_NONSTD  3 +  constant KBD_REMRESETHANDLER
CMD_NONSTD  4 +  constant KBD_RESETHANDLERDONE

.THEN
