\ AMIGA JForth Include file.
decimal
EXISTS? RESOURCES_BATTMEMBITSAMIGA_H NOT .IF
1   constant RESOURCES_BATTMEMBITSAMIGA_H
0   constant BATTMEM_AMIGA_AMNESIA_ADDR
1   constant BATTMEM_AMIGA_AMNESIA_LEN

1   constant BATTMEM_SCSI_TIMEOUT_ADDR
1   constant BATTMEM_SCSI_TIMEOUT_LEN

2   constant BATTMEM_SCSI_LUNS_ADDR
1   constant BATTMEM_SCSI_LUNS_LEN

.THEN
