\ AMIGA JForth Include file.
decimal
EXISTS? RESOURCES_BATTMEMBITSSHARED_H NOT .IF
1   constant RESOURCES_BATTMEMBITSSHARED_H
64   constant BATTMEM_SHARED_AMNESIA_ADDR
1   constant BATTMEM_SHARED_AMNESIA_LEN

65   constant BATTMEM_SCSI_HOST_ID_ADDR
3   constant BATTMEM_SCSI_HOST_ID_LEN

68   constant BATTMEM_SCSI_SYNC_XFER_ADDR
1   constant BATTMEM_SCSI_SYNC_XFER_LEN

.THEN
